### PR TITLE
Group commands into categories

### PR DESCRIPTION
**Pull request by dimtrovich**
see https://github.com/adhocore/php-cli/issues/68

### CODE REVIEW

**Comment by adhocore** [comment]
thanks a lot, would you wait a lite for me to review it sometimes next week :)

**Comment by adhocore** [comment]
btw what do you think about this? https://github.com/adhocore/php-cli/pull/new/68-command-group  (i had hacked on this before seeing your PR)

image

---
```php
<?php

$app = new Ahc\Cli\Application('console', '0.0.1');

$app
    ->command('db:create', 'db create', 'dc')->tap()
    ->command('app:init', 'app init', 'ai')->tap()
    ->command('routelist', 'route list', 'rl')->tap()
    ->command('db:seed', 'db seed', 'ds')->tap()
    ->command('routegen', 'route gen', 'rg')->tap()
    ->command('app:env', 'app env', 'ae')->tap()
;

$app->handle($_SERVER['argv'] ?? []);
```

**Comment by dimtrovich** [comment]
> thanks a lot, would you wait a little for me to review it sometimes next week :)

Hi!!! I've been waiting for your response ever since!!! have you forgotten 😒😢

**Comment by adhocore** [comment]
helo, i was going thru rough times lately.
would you pls try to align the approach and styling similar to https://github.com/adhocore/php-cli/pull/new/68-command-group

**Comment by adhocore** [comment]
hi, could you pls try to apply the feedback, add docs to readme and make the build pass? so i can accept the PR as hacktoberfest-accepted on your behalf.
(or if you lost interest on it then we can close this PR as well)

**Comment by dimtrovich** [comment]
ok, I'll put the comments on all my edits.
for code alignment, it would be interesting if you set up a coding style (with cs-fixer for example)

**Comment by adhocore** [comment]
i think you misunderstood. i meant this:
> would you pls try to align the approach and styling similar to [adhocore/php-cli/pull/new/68-command-group](https://github.com/adhocore/php-cli/pull/new/68-command-group)
(it would be nice to have as little code change as possible)

**Comment by adhocore** [comment]
helo @dimtrovich , i have fixed it in #72, and released [v1.2.0](https://github.com/adhocore/php-cli/releases/tag/v1.2.0) with credits to you as well

**Pull request closed without merging**
