### PR TITLE
Feat add spinner to output

### PR DESCRIPTION
**Pull request by dimtrovich**
proposal of a spinner for the output following an issue.

see https://github.com/adhocore/tusc.sh/issues/3#issuecomment-1597044193

### CODE REVIEW

**Comment by dimtrovich** [comment]
decidedly still can't quite understand the logic of the tests with phpunit. My tests all messed up 😥😓😭😭

**Comment by adhocore** [comment]
@dimtrovich thank you very much i think spinner needs to be asynchronous, is it possible with current implementation?

progress bar is when we know how many items we have to process already so we can know exact progress to show the bar.

spinner is when we don't know that in advance so we just let is spin, perform some long task that take arbitrary time, then on finish stop spinner.

**Comment by adhocore** [comment]
@dimtrovich can we close it? :D

**Comment by dimtrovich** [comment]
Hello @adhocore. Sorry for the delay.
The idea of a plugin is a good one, but at the moment the package doesn't offer any mechanism for creating extensions. This idea could be implemented in v2!!!

The other problem I have with this is that it will be quite difficult to capture your hard-coded text and then translate it... There's a bit of text in all the classes and also between the special formatting tags (for example, in the error stack display method, like `<red>Thrown In<end/>:`).

With this, I think it will be impossible to externalize the translation system. On the other hand, you could remove the translation files and leave just English, and the developer who wants a different language could extend it as I mentioned in the Readme

**Comment by dimtrovich** [comment]
> @dimtrovich can we close it? :D

for the moment, I think we can close it. I haven't found a way of doing it as simply as possible. 
the approach i saw that seemed good was to use `react php` for asynchronous processes. but we can't afford to use third-party libraries in package

**Pull request closed without merging**
